Refactoring of the basic client module
rico-projects/rico-projector pull request #25
Opened 2019-07-01 09:43 UTC by hendrikebbers

- final
- null checks
- comment code removed
- TODOs that should be discussed

2019-07-01 09:44 UTC, hendrikebbers commented
Maybe this has some duplicate changes with #23 that should be merged before this PR is merged. #23 can be merged once @joha78 reacted in then small review requests I did earlier today.

2019-07-01 20:19 UTC, madmas commented
Overall, looks good to me and I agree that #23 needs to be merged first.*
*But* please  remove all Todo comments from the code before merge, either we should solve them within the PR or transfer each topic into an issue

2019-07-03 08:37 UTC, joha78 requested changes

2019-07-03 08:37 UTC, joha78 commented on base/client/src/main/java/dev/rico/internal/client/projector/JavaFXProjectorImpl.java
> +        //TODO: Discussion if this really makes sense...
the return null is for this case:
```
BorderPaneModel borderPaneModel = ui().borderPane();
        borderPaneModel.setCenter(something);
        borderPaneModel.setCenter(null);
```

2019-07-03 08:37 UTC, joha78 commented on base/client/src/main/java/dev/rico/internal/client/projector/dialoghandler/DialogConfiguration.java
> +    //TODO: Method not referenced. Can we remove it?
Can be removed

2019-07-03 08:37 UTC, joha78 commented on base/client/src/main/java/dev/rico/internal/client/projector/dialoghandler/ShutdownDialogHandler.java
> +//TODO: How should we handle this one?
will be removed by @joha78

2019-07-03 08:37 UTC, joha78 commented on base/client/src/main/java/dev/rico/internal/client/projector/mixed/Configuration.java
> +//TODO: Class is not used, can we delete it?
Will be removed by @joha78

2019-07-03 08:37 UTC, joha78 commented on base/client/src/main/java/dev/rico/internal/client/projector/uimanager/AsyncSequence.java
> +//TODO: This class is not used. Can we delete it?
Will be removed by @joha78

2019-07-03 08:37 UTC, joha78 commented on base/client/src/main/java/dev/rico/internal/client/projector/uimanager/ImageViewer.java
> +//TODO: Looks like a factory / presenter for this class is missing. Should we remove it?
Will be removed by @joha78

2019-07-03 08:37 UTC, joha78 commented on base/client/src/main/java/dev/rico/internal/client/projector/uimanager/UnexpectedErrorDialog.java
>  }
Messages should be configurable

2019-07-09 13:56 UTC, madmas requested changes
* remove TODO (convert into issues or solve)
* solve open discussions 

;-)

2019-07-29 14:35 UTC, merged